-- Custom app launch bindings
o.bind("SUPER + RETURN", "Terminal", "$terminal --dir=\"$(omarchy-cmd-terminal-cwd)\"")
o.bind("SUPER + ALT + RETURN", "Tmux", "exec, uwsm-app -- xdg-terminal-exec --dir=\"$(omarchy-cmd-terminal-cwd)\" tmux new")
o.bind("SUPER + SHIFT + F", "File manager", "uwsm app -- nautilus --new-window")
o.bind("SUPER + B", "Browser", "$browser")
o.bind("SUPER + SHIFT + B", "Browser (private)", "$browser --private")
o.bind("SUPER + M", "Music", "omarchy-launch-or-focus spotify")
o.bind("SUPER + N", "Editor", "omarchy-launch-editor")
o.bind("SUPER + S", "Activity", "omarchy-launch-tui btop")
o.bind("SUPER + D", "Docker", "omarchy-launch-tui lazydocker")
o.bind("SUPER + G", "Signal", "omarchy-launch-or-focus signal \"uwsm app -- signal-desktop\"")
o.bind("SUPER + O", "Obsidian", "omarchy-launch-or-focus obsidian \"uwsm-app -- obsidian\"")
o.bind("SUPER + SLASH", "Passwords", "uwsm app -- 1password")
o.bind("SUPER + SHIFT + S", "Sober", "flatpak run org.vinegarhq.Sober")
o.bind("SUPER + A", "ChatGPT", "omarchy-launch-webapp \"https://chatgpt.com\"")
o.bind("SUPER + SHIFT + A", "Grok", "omarchy-launch-webapp \"https://grok.com\"")
o.bind("SUPER + C", "Calendar", "$terminal --class=Impala -e impala")
o.bind("SUPER + E", "Email", "omarchy-launch-webapp \"https://app.hey.com\"")
o.bind("SUPER + Y", "YouTube", "omarchy-launch-or-focus-webapp YouTube \"https://youtube.com/\"")
o.bind("SUPER + SHIFT + G", "WhatsApp", "omarchy-launch-or-focus-webapp WhatsApp \"https://web.whatsapp.com/\"")
o.bind("SUPER + ALT + G", "Google Messages", "omarchy-launch-or-focus-webapp \"Google Messages\" \"https://messages.google.com/web/conversations\"")
o.bind("SUPER + SHIFT + T", "Tailscale", "omarchy-launch-tui sudo tsui")
